SquareSolver: Square_tests.h File Reference
Square_tests.h File Reference
Classes
struct Test
Number of tests.
Functions
void test_question (void)
Asks the user if the program needs to be tested.
int count_lines (const char filename[])
int TestOne (const struct Test *tests_params, struct Roots *roots)
void TestAll (void)
Does some tests.
void test_file (const char filename[])
Function Documentation
count_lines()
int count_lines (const char filename[])
РЎounts the number of lines in the file
Parameters
filename[] Name of the transferred file
Definition at line 82 of file Square_tests.cpp.
{
     FILE* file_test = fopen(filename, "r");
     int lines_count = 0;
     while (!feof(file_test)) {
         if (fgetc(file_test) == '\n')
             lines_count++;
     }
     fclose(file_test);
     return lines_count;
 }
Referenced by test_file().
test_file()
void test_file (const char filename[])
Reads the data for the program test and tests it
Parameters
filename[] Name of the test file
Definition at line 117 of file Square_tests.cpp.
{
     FILE* file_tests = fopen(filename, "r");
     if (file_tests == NULL) {
         printf("РџРѕСЃР»Рµ -t РІС‹ РґРѕР»Р¶РЅС‹ СѓРєР°Р·С‹РІР°С‚СЊ С„Р°Р№Р» СЃ С‚РµСЃС‚Р°РјРё, РµСЃР»Рё РІС‹ СЃРґРµР»Р°Р»Рё СЌС‚Рѕ, "
                                 "Р·РЅР°С‡РёС‚ РІР°С€ С„Р°Р№Р» РЅРµ РІ СЌС‚РѕР№ РїР°РїРєРµ, РїСЂРѕРіСЂР°РјРјР° РЅРµ РЅР°С€Р»Р° РµРіРѕ.\n");
         return;
     }
     const int NLINES = count_lines(filename);
     int correct_tests = 0;
     for (int i = 0; i < NLINES; i++) {
         struct Test tests_params = {};
         struct Roots roots = {};
         if (fscanf(file_tests, "%lf %lf %lf %lf %lf %d", &tests_params.a, &tests_params.b, &tests_params.c,
               &tests_params.x1, &tests_params.x2, &tests_params.count_solutions) != 6) {
             printf("РќРµРєРѕСЂСЂРµРєС‚РЅС‹Р№ С„Р°Р№Р» СЃ С‚РµСЃС‚Р°РјРё. РќРѕРјРµСЂ СЃС‚СЂРѕРєРё СЃ РЅРµРєРѕСЂСЂРµРєС‚РЅС‹РјРё РґР°РЅРЅС‹РјРё: %d\n", i + 1);
             exit(0);
         }
         correct_tests += TestOne(&tests_params, &roots);
     }
     fclose(file_tests);
     printf("РљРѕР»РёС‡РµСЃС‚РІРѕ РїСЂР°РІРёР»СЊРЅС‹С… С‚РµСЃС‚РѕРІ: %d\n"
            "РљРѕР»РёС‡РµСЃС‚РІРѕ РїСЂРѕР№РґРµРЅРЅС‹С… С‚РµСЃС‚РѕРІ: %d\n", correct_tests, NLINES);
 }
References Test::a, Test::b, Test::c, count_lines(), Test::count_solutions, TestOne(), Test::x1, and Test::x2.
Referenced by command_check().
test_question()
void test_question (void)
Asks the user if the program needs to be tested.
Definition at line 99 of file Square_tests.cpp.
{
     printf("РҐРѕС‚РёС‚Рµ Р»Рё РІС‹ РїСЂРѕРІРµСЂРёС‚СЊ СЂР°Р±РѕС‚Сѓ РїСЂРѕРіСЂР°РјРјС‹?\n"
            "Р’РІРµРґРёС‚Рµ 1, РµСЃР»Рё С…РѕС‚РёС‚Рµ, Рё С‡С‚Рѕ СѓРіРѕРґРЅРѕ, РµСЃР»Рё РІС‹ РґРѕРІРµСЂСЏРµС‚Рµ РїСЂРѕРіСЂР°РјРјРµ.\n");
     int answer = 0;
     scanf("%d", &answer);
     if (answer == 1) {
         TestAll();
     }
     else {
         clear_buf();
     }
 }
References clear_buf(), and TestAll().
Referenced by command_check().
TestAll()
void TestAll (void)
Does some tests.
Definition at line 52 of file Square_tests.cpp.
                    {
     #define CREAT_TEST TestOne(&tests_params[i], &roots)
     int count_correct_tests = 0;
     struct Test tests_params[] = {{1, 2,  1, -1, -1, 1},
                                   {2, 2, -4,  1, -2, 2},
                                   {0, 0,  0,  0,  0, INFINITE_SOLUTIONS},
                                   {0, 0,  6,  0,  0, 0},
                                   {0, 2, -4,  2,  2, 1},
                                   {1, 0, -4,  2, -2, 2},
                                   {2, 0,  0,  0,  0, 1}};
     const size_t N_TESTS = sizeof(tests_params) / sizeof(tests_params[0]);
     for(size_t i = 0; i < N_TESTS; i++) {
         struct Roots roots;
         count_correct_tests += CREAT_TEST;
     }
     #undef CREAT_TEST
     printf("РљРѕР»РёС‡РµСЃС‚РІРѕ РїСЂР°РІРёР»СЊРЅС‹С… С‚РµСЃС‚РѕРІ: %d\n"
                "РљРѕР»РёС‡РµСЃС‚РІРѕ РїСЂРѕР№РґРµРЅРЅС‹С… С‚РµСЃС‚РѕРІ: %d\n", count_correct_tests, N_TESTS);
 }
References CREAT_TEST, and INFINITE_SOLUTIONS.
Referenced by test_question().
TestOne()
int TestOne (const struct Test * tests_params, struct Roots * roots)
Testing the program
Parameters
[in] tests_params Variable transmitting test parameters
[in] refroots An object of the Roots structure containing the correct roots of the equation and the correct number of roots
Definition at line 10 of file Square_tests.cpp.
{
     assert(tests_params != NULL);
     assert(roots != NULL);
     assert(isfinite(tests_params->a));
     assert(isfinite(tests_params->b));
     assert(isfinite(tests_params->c));
     assert(isfinite(tests_params->x1));
     assert(isfinite(tests_params->x2));
     struct SquareTrinomial coeffs = {tests_params->a, tests_params->b, tests_params->c};
     square_solver(&coeffs, roots);
     if (!f_comparison(roots->x1, tests_params->x1) ||
         !f_comparison(roots->x2, tests_params->x2) ||
         roots->count_solutions != tests_params->count_solutions) {
         HANDLE  hConsole;
         hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
         SetConsoleTextAttribute(hConsole, FOREGROUND_RED);
         printf("Failed:   x1 = %lf, x2 = %lf, count_solutions = %d\n"
                "Expected: x1 = %lf, x2 = %lf, count_solutions = %d\n", roots->x1, roots->x2,
                 roots->count_solutions, tests_params->x1, tests_params->x2, tests_params->count_solutions);
         SetConsoleTextAttribute(hConsole, WHITE);
         return 0;
     }
     else {
         HANDLE  hConsole;
         hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
         SetConsoleTextAttribute(hConsole, FOREGROUND_GREEN);
         printf("Test OK.\n");
         SetConsoleTextAttribute(hConsole, WHITE);
         return 1;
     }
 }
References Test::a, Test::b, Test::c, Test::count_solutions, Roots::count_solutions, f_comparison(), square_solver(), WHITE, Test::x1, Roots::x1, Test::x2, and Roots::x2.
Referenced by test_file().