SquareSolver: Square_solver.h File Reference
Square_solver.h File Reference
Functions
bool is_zero (double n)
bool is_greater_than_zero (double n)
bool f_comparison (double x, double y)
void square_solver (const struct SquareTrinomial *coeffs, struct Roots *roots)
void linear_solver (const struct SquareTrinomial *coeffs, struct Roots *roots)
Variables
const double EPSILON = 1e-6
Accuracy of comparison.
Function Documentation
f_comparison()
bool f_comparison (double x, double y)
Comparison of float numbers
Parameters
[in] x A float number
[in] y A float number
Definition at line 25 of file Square_solver.cpp.
{
     assert(isfinite(x));
     assert(isfinite(y));
     return fabs(x - y) < EPSILON;
 }
References EPSILON.
Referenced by TestOne().
is_greater_than_zero()
bool is_greater_than_zero (double n)
Check: is the float number greater than zero
Parameters
[in] n A float number that is compared to zero
Definition at line 17 of file Square_solver.cpp.
{
     assert(isfinite(n));
     return n > EPSILON;
 }
References EPSILON.
Referenced by square_solver().
is_zero()
bool is_zero (double n)
Comparing a float number with zero
Parameters
[in] n A float number that is compared to zero
Definition at line 8 of file Square_solver.cpp.
{
     assert(isfinite(n));
     return fabs(n) < EPSILON;
 }
References EPSILON.
Referenced by linear_solver(), and square_solver().
linear_solver()
void linear_solver (const struct SquareTrinomial * coeffs, struct Roots * roots)
Calculation of the root of a nonlinear equation
Parameters
[in] coeffs An object of the SquareTrinomial structure containing the coefficients of the square equation
[out] roots An object of the Roots structure containing the roots of the equation and the number of rootsР№
Definition at line 34 of file Square_solver.cpp.
{
     assert(coeffs != NULL);
     assert(roots  != NULL);
     if (!is_zero(coeffs->b)) {
         roots->x1 = -coeffs->c / coeffs->b;
         roots->x1 = (is_zero(roots->x1)) ? 0 : roots->x1;
         roots->x2 = roots->x1;
         roots->count_solutions = 1;
     }
     else {
         roots->count_solutions = (is_zero(coeffs->c)) ? INFINITE_SOLUTIONS : 0;
     }
 }
References SquareTrinomial::b, SquareTrinomial::c, Roots::count_solutions, INFINITE_SOLUTIONS, is_zero(), Roots::x1, and Roots::x2.
Referenced by square_solver().
square_solver()
void square_solver (const struct SquareTrinomial * coeffs, struct Roots * roots)
Calculation of the roots of the equation
Parameters
[in] coeffs An object of the SquareTrinomial structure containing the coefficients of the square equation
[out] roots An object of the Roots structure containing the roots of the equation and the number of roots
Definition at line 52 of file Square_solver.cpp.
{
     assert(coeffs != NULL);
     assert(roots != NULL);
     assert(isfinite(coeffs->a));
     assert(isfinite(coeffs->b));
     assert(isfinite(coeffs->c));
     *roots = {0, 0, -1};
     if (!is_zero(coeffs->a)) {
         const double d = coeffs->b * coeffs->b - 4 * coeffs->a * coeffs->c;
         if (is_greater_than_zero(d)) {
             const double d_sqrt = sqrt(d);
             roots->x1 = (-coeffs->b + d_sqrt) / (2 * coeffs->a);
             roots->x2 = (-coeffs->b - d_sqrt) / (2 * coeffs->a);
             roots->count_solutions = 2;
         }
         else if (is_zero(d)) {
             roots->x1 = -coeffs->b / (2 * coeffs->a);
             roots->x1 = (is_zero(roots->x1)) ? 0 : roots->x1;
             roots->x2 = roots->x1;
             roots->count_solutions = 1;
         }
         else {
             roots->count_solutions = 0;
         }
     }
     else
         linear_solver(coeffs, roots);
 }
References SquareTrinomial::a, SquareTrinomial::b, SquareTrinomial::c, Roots::count_solutions, is_greater_than_zero(), is_zero(), linear_solver(), Roots::x1, and Roots::x2.
Referenced by main(), and TestOne().
Variable Documentation
EPSILON
const double EPSILON = 1e-6
Accuracy of comparison.
Definition at line 5 of file Square_solver.h.
Referenced by f_comparison(), is_greater_than_zero(), and is_zero().