SquareSolver: Square_main.cpp File Reference
Square_main.cpp File Reference
#include <TXLib.h>
#include "Square_types.h"
#include "Square_io.h"
#include "Square_solver.h"
#include "Square_tests.h"
#include <stdio.h>
#include <math.h>
#include <windows.h>
#include <assert.h>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 24 of file Square_main.cpp.
{
     introduction();
     command_check(argc, argv);
     struct Roots roots = {};
     struct SquareTrinomial coeffs = {};
     square_input(&coeffs);
     square_solver(&coeffs, &roots);
     square_print(&roots);
     return 0;
 }
References command_check(), introduction(), square_input(), square_print(), and square_solver().