SquareSolver: Square_io.cpp File Reference
Square_io.cpp File Reference
#include "Square_types.h"
#include "Square_io.h"
#include "Square_tests.h"
#include <stdio.h>
#include <stdlib.h>
#include <windows.h>
#include <assert.h>
#include <math.h>
Functions
void introduction (void)
Brief program description.
void help (void)
Description of the program.
void command_check (int argc, char *argv[])
void eof_control (const int c)
void clear_buf (void)
Clearing the input buffer.
void square_input (struct SquareTrinomial *coeffs)
void square_print (const struct Roots *roots)
Function Documentation
clear_buf()
void clear_buf (void)
Clearing the input buffer.
Definition at line 70 of file Square_io.cpp.
                      {
     int c = getchar();
     while((c = getchar()) != '\n') {
         eof_control(c);
     }
 }
References eof_control().
Referenced by square_input(), and test_question().
command_check()
void command_check (int argc, char * argv[])
РЎhecks the command line for keywords
Parameters
[in] argc Number of lines entered from the command line
[in] argv List of entered lines from the command line
Definition at line 33 of file Square_io.cpp.
{
     bool is_test = false;
     for (int i = 0; i < argc; i++) {
         if (strcmp(argv[i], "-t") == 0) {
             test_file(argv[i + 1]);
             is_test = true;
         }
         else if (strcmp(argv[i], "--help") == 0) {
             help();
         }
     }
     if (!is_test) {
             test_question();
         }
 }
References help(), test_file(), and test_question().
Referenced by main().
eof_control()
void eof_control (const int c)
If find EOF, will terminate the program
Parameters
[in] c Symbol from the input buffer
Definition at line 58 of file Square_io.cpp.
{
     if (c == EOF) {
         printf("Р—Р°С‡РµРј РІС‹ РІРІРµР»Рё EOF?\n"
                "Р­С‚Р° РїСЂРѕРіСЂР°РјРјР° Р±СѓРґРµС‚ Р·Р°РІРµСЂС€РµРЅР°.\n");
         exit(0);
     }
 }
Referenced by clear_buf().
help()
void help (void)
Description of the program.
Definition at line 16 of file Square_io.cpp.
                 {
     printf("\n\nРљСЂР°С‚РєРѕРµ РѕРїРёСЃР°РЅРёРµ СЂР°Р±РѕС‚С‹ РїСЂРѕРіСЂР°РјРјС‹:\n"
            "Р’ РЅР°С‡Р°Р»Рµ РІР°СЃ СЃРїСЂРѕСЃСЏС‚ С…РѕС‚РёС‚Рµ Р»Рё РІС‹ РїСЂРѕС‚РµСЃС‚РёСЂРѕРІР°С‚СЊ РїСЂРѕРіСЂР°РјРјСѓ. "
                             "Р•СЃР»Рё РґР°, С‚Рѕ РѕРЅР° РїСЂРѕС‚РµСЃС‚РёСЂСѓРµС‚СЃСЏ, РµСЃР»Рё РЅРµС‚ - РїРѕР№РґС‘С‚ РґР°Р»СЊС€Рµ.\n"
            "Р—Р°С‚РµРј РїРѕРїСЂРѕСЃРёС‚ РІРІРµСЃС‚Рё РІР°СЃ РєРѕСЌС„С„РёС†РёРµРЅС‚С‹ РєРІР°РґСЂР°С‚РЅРѕРіРѕ СѓСЂР°РІРЅРµРЅРёСЏ, "
                             "РїРѕСЃР»Рµ РІРІРѕРґР° РІР°Рј РІС‹РІРµРґСѓС‚СЃСЏ РєРѕСЂРЅРё СѓСЂР°РІРЅРµРЅРёСЏ.\n"
            "-t Filename Р’РєР»СЋС‡Р°РµС‚ С‚РµСЃС‚С‹ РїСЂРѕРіСЂР°РјРјС‹. Р’ С„Р°Р№Р»Рµ РґРѕР»Р¶РЅС‹ Р±С‹С‚СЊ РїРѕ РїРѕСЂСЏРґРєСѓ "
                             "СЃРЅР°С‡Р°Р»Р° РєРѕСЌС„С„РёС†РёРµРЅС‚С‹ СѓСЂР°РІРЅРµРЅРёСЏ, Р·Р°С‚РµРј РєРѕСЂРЅРё Рё РёС… РєРѕР»РёС‡РµСЃС‚РІРѕ.\n"
            "Р‘РµСЃРєРѕРЅРµС‡РЅРѕРµ РјРЅРѕР¶РµСЃС‚РІРѕ СЂРµС€РµРЅРёР№ СЃС‡РёС‚Р°РµС‚СЃСЏ С‚СЂРѕР№РєРѕР№.\nР•СЃР»Рё РєРѕСЂРµРЅСЊ РѕРґРёРЅ, С‚Рѕ РѕР±Р° РєРѕСЂРЅСЏ РѕРґРёРЅР°РєРѕРІС‹.\n"
            "Р•СЃР»Рё РєРѕСЂРЅСЏ РЅРµС‚, РѕРЅ СЃС‡РёС‚Р°РµС‚СЃСЏ РЅСѓР»С‘Рј.\n\n");
 }
Referenced by command_check().
introduction()
void introduction (void)
Brief program description.
Definition at line 10 of file Square_io.cpp.
{
     printf("Р­С‚Р° РїСЂРѕРіСЂР°РјРјР° СЂРµС€Р°РµС‚ РєРІР°РґСЂР°С‚РЅРѕРµ СѓСЂР°РІРЅРµРЅРёРµ\n");
 }
Referenced by main().
square_input()
void square_input (struct SquareTrinomial * coeffs)
Entering the coefficients of the equation
Parameters
[out] coeffs An object of the SquareTrinomial structure containing the coefficients of the square equation
Definition at line 81 of file Square_io.cpp.
{
     assert(coeffs != NULL);
     assert(isfinite(coeffs->a));
     assert(isfinite(coeffs->b));
     assert(isfinite(coeffs->c));
     printf("Р’РІРµРґРёС‚Рµ РєРѕСЌС„С„РёС†РёРµРЅС‚С‹ РєРІР°РґСЂР°С‚РЅРѕРіРѕ СѓСЂР°РІРЅРµРЅРёСЏ: ");
     while(scanf("%lf %lf %lf", &coeffs->a, &coeffs->b, &coeffs->c) != 3) {
         clear_buf();
         HANDLE  hConsole;
         hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
         SetConsoleTextAttribute(hConsole, FOREGROUND_RED);
         printf("Р’С‹ РІРІРµР»Рё РЅРµРєРѕСЂСЂРµРєС‚РЅС‹Рµ РґР°РЅРЅС‹Рµ."
                     " Р’С‹ РґРѕР»Р¶РЅС‹ РІРІРµСЃС‚Рё 3 С‡РёСЃР»Р° С‡РµСЂРµР· РїСЂРѕР±РµР»С‹, РїРѕРїСЂРѕР±СѓР№С‚Рµ СЃРЅРѕРІР°: ");
         SetConsoleTextAttribute(hConsole, WHITE);
     }
 }
References SquareTrinomial::a, SquareTrinomial::b, SquareTrinomial::c, clear_buf(), and WHITE.
Referenced by main().
square_print()
void square_print (const struct Roots * roots)
Answer output
Parameters
[in] roots An object of the Roots structure containing the roots of the equation and the number of roots
Definition at line 106 of file Square_io.cpp.
{
     assert(roots != NULL);
     assert(isfinite(roots->x1));
     assert(isfinite(roots->x2));
     switch(roots->count_solutions) {
         case 0:
             printf("РЈ РґР°РЅРЅРѕРіРѕ СѓСЂР°РІРЅРµРЅРёСЏ РЅРµС‚ РєРѕСЂРЅРµР№ РІ РґРµР№СЃС‚РІРёС‚РµР»СЊРЅС‹С… РІРµР»РёС‡РёРЅР°С….\n");
             break;
         case 1:
             printf("РљРѕСЂРµРЅСЊ СѓСЂР°РІРЅРµРЅРёСЏ: %.*lf\n", DIGITS_AFTER_POINT, roots->x1);
             break;
         case 2:
             printf("РљРѕСЂРЅРё СѓСЂР°РІРЅРµРЅРёСЏ: %.*lf %.*lf\n", DIGITS_AFTER_POINT, roots->x1,
                     DIGITS_AFTER_POINT, roots->x2);
             break;
         default:
             printf("Р‘РµСЃРєРѕРЅРµС‡РЅРѕРµ РјРЅРѕР¶РµСЃС‚РІРѕ СЂРµС€РµРЅРёР№.");
             break;
     }
 }
References Roots::count_solutions, DIGITS_AFTER_POINT, Roots::x1, and Roots::x2.
Referenced by main().